services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: words_ai_app
    ports:
      - "8000:8000"
    environment:
      - AI_CREDENTIALS=${AI_CREDENTIALS}
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]